### ISSUE TITLE
'bosh create release' fails with 404 error when downloading blobs

### ISSUE THREAD

**Issue by grenzr** [minio/minio-boshrelease#1]
On attempting to create a local tarball of the official minio bosh release using `bosh create release releases/minio/minio-2.yml --with-tarball`, we couldnt download the blobs as it returned:

```
Recreating release from the manifest
Downloading from blobstore (id=8fc7e582-52b7-4780-b07b-aef6190235b5)...
Blobstore error: Could not fetch object, 404/
```

**Comment by donatello** [comment]
Thank you for reporting the issue. We are working on resolving this ASAP.

**Comment by donatello** [comment]
@grenzr We migrated our blob-storage to CloudFoundry's community S3 account now. This issue is now resolved.

**Comment by grenzr** [comment]
Hi guys,

Thanks for looking into this for us, although trying the same thing again now shows a 403 error.

Any chance you can make this bucket public readable?

Thanks,

Ryan

**Comment by donatello** [comment]
@grenzr 
> Any chance you can make the blobs you've put into this bucket public readable?

Done. Please let me know if there are any more issues.
