### ISSUE TITLE
Review manifest files

### ISSUE THREAD

**Issue by nitisht** [minio/minio-boshrelease#11]
`manfest-fs.yaml` and `manifest-dist-4node.yaml` needs to be renamed to `manfest-fs-example.yaml` and `manifest-dist-example.yaml` 

- Needs to be reviewed to update the file names and check hard coded values. 
- Review yhy multiple IPs in fs, BOSH
- Explore if both files can be merged

**Comment by krishnasrinivas** [comment]
> Needs to be reviewed to update the file names and check hard coded values.

file names can be made as manfest-fs-example.yaml and manifest-dist-example.yaml
Also there is no hardcoding now, can you check.

> Review yhy multiple IPs in fs, BOSH

IPs are removed from the manifest files now, as it is assigned automatically by bosh director

> Explore if both files can be merged

```
krishna@escape:~/dev/minio-boshrelease$ diff manifests/manifest-*
17c17
<   instances: 4
---
>   instances: 1
krishna@escape:~/dev/minio-boshrelease$ 
```
this is the only differing line because of which it can't be merged
