### ISSUE TITLE
Is Minio compatible with Xenial?

### ISSUE THREAD

**Issue by brightzheng100** [minio/minio-boshrelease#117]
I added a simple ops file to update the manifest by using `xenial` stemcell and sounds it works as well.

``` shell
$ cat > stemcell.yml <<EOF
- type: replace
  path: /stemcells/alias=default/os
  value: ubuntu-xenial
EOF

$ bosh deploy -d minio manifests/manifest-fs-example.yml \
    -o stemcell.yml \
    -v minio_deployment_name=minio \
    -v minio_accesskey=admin \
    -v minio_secretkey=MYPASSWORD

$ bosh vms
...
Deployment 'minio'

Instance                                    Process State  AZ  IPs        VM CID                                   VM Type  Active
minio/268d8d66-7e2a-4835-b794-b0b3a9b5ab02  running        z1  10.0.0.23  vm-b8c96b98-4b9b-43d5-77ef-aa76e9423512  default  true

1 vms

$ mc config host add minio http://10.0.0.23:9000 admin MYPASSWORD
$ mc mb minio/abc
Bucket created successfully `minio/abc`.
$ mc ls minio/
[2018-12-27 10:26:06 UTC]     0B abc/
```

As Trusty is going to retire very soon so I appreciate if you guys can help to perform a thorough test and confirm that. Thank you!

**Comment by krishnasrinivas** [comment]
@brightzheng100 minio is compatible with Xenial, actually since minio is written in Go it is statically compiled without any external dependency.

**Comment by brightzheng100** [comment]
Great you've confirmed at this @krishnasrinivas 
Actually I've using Xenial for `minio-boshrelease` for a while and it works perfectly well so far.

Will send a PR accordingly soon.
