### ISSUE TITLE
https is giving errors in monit

### ISSUE THREAD

**Issue by Klojo** [minio/minio-boshrelease#118]
Hello

for security reasons we must switch form http:// to https:// 
can you help us to resolve this issue.

Minio Deployment
Name                               Release(s)                     Stemcell(s)                                       
minio-backup-writer        capi/1.75.0                   bosh-vsphere-esxi-ubuntu-trusty-go_agent/3586.67  
                                         minio/2019-01-16T21-44-08Z

Start Minio Bosh Deploy
Task 3633404

Task 3633404 | 12:53:26 | Preparing deployment: Preparing deployment (00:00:00)
Task 3633404 | 12:53:27 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 3633404 | 12:53:27 | Updating instance minio: minio/968e3577-0861-4737-a2aa-c109802d2361 (0) (canary) (00:00:03)
                     L Error: Action Failed get_task: Task ae658ac1-565e-4feb-6dff-21a606ecbd3d result: Stopping Monitored Services: Stop all services: Running command: 'monit stop -g vcap', stdout: '', stderr: '/var/vcap/monit/job/0001_minio-server.monitrc:11: Error: syntax error 'https'
': exit status 1
Task 3633404 | 12:53:30 | Error: Action Failed get_task: Task ae658ac1-565e-4feb-6dff-21a606ecbd3d result: Stopping Monitored Services: Stop all services: Running command: 'monit stop -g vcap', stdout: '', stderr: '/var/vcap/monit/job/0001_minio-server.monitrc:11: Error: syntax error 'https'
': exit status 1

Task 3633404 Started  Mon Jan 21 12:53:26 UTC 2019
Task 3633404 Finished Mon Jan 21 12:53:30 UTC 2019
Task 3633404 Duration 00:00:04
Task 3633404 error

Updating deployment:
  Expected task '3633404' to succeed but state is 'error'

Exit code 1

ssh to minio server shows this error:
/var/vcap/monit/job/0001_minio-server.monitrc:11: Error: syntax error 'https'

**Comment by gmrodgers** [comment]
Hey @poornas and @kannappanr,

We are experiencing the same issue when we consumed the latest version of these release.  It is currently breaking our pipeline. We get the same error output and here is the monit file that is templated:

```
check process minio-server
  with pidfile /var/vcap/sys/run/minio-server/pid
  start program "/var/vcap/jobs/minio-server/bin/ctl start"
  stop program "/var/vcap/jobs/minio-server/bin/ctl stop"
  group vcap
  if failed host localhost port 9000 protocol https
      and request '/minio/health/live'
      with timeout 60 seconds for 5 cycles
  then restart
```

Feel free to reach out to us if you need more info.

Thanks,
@terminatingcode and Glen

**Comment by Proplex** [comment]
We're also experiencing this issue; as a result the deploy fails because Monit never brings up the BOSH agent.

```
Task 3 | 16:22:08 | Preparing deployment: Preparing deployment (00:00:09)
Task 3 | 16:22:17 | Preparing deployment: Rendering templates (00:00:01)
Task 3 | 16:22:18 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 3 | 16:22:18 | Compiling packages: mc/9aec040abc483f99a6d6067b6030659370363a62c96defa93a00ae6af94ac884
Task 3 | 16:22:18 | Compiling packages: minio/bdb0a728b65ec9e2c82d8a19abe3da74c637fdabc4bdf89b12fbd281b669e7ff
Task 3 | 16:24:13 | Compiling packages: mc/9aec040abc483f99a6d6067b6030659370363a62c96defa93a00ae6af94ac884 (00:01:55)
Task 3 | 16:24:28 | Compiling packages: minio/bdb0a728b65ec9e2c82d8a19abe3da74c637fdabc4bdf89b12fbd281b669e7ff (00:02:10)
Task 3 | 16:24:52 | Creating missing vms: minio/64544db8-6334-4731-9adb-4769bce79c3f (0) (00:01:11)
Task 3 | 16:26:04 | Updating instance minio: minio/64544db8-6334-4731-9adb-4769bce79c3f (0) (canary) (00:01:59)
                   L Error: Timed out sending 'start' to instance: 'minio/64544db8-6334-4731-9adb-4769bce79c3f', agent-id: 'c623ce17-2b32-46a7-805e-9e148c95302e' after 45 seconds
Task 3 | 16:28:03 | Error: Timed out sending 'start' to instance: 'minio/64544db8-6334-4731-9adb-4769bce79c3f', agent-id: 'c623ce17-2b32-46a7-805e-9e148c95302e' after 45 seconds
```

```
minio/64544db8-6334-4731-9adb-4769bce79c3f:/var/vcap/bosh_ssh/bosh_8215cf708a6f420# monit summary
/var/vcap/monit/job/0000_minio-server.monitrc:11: Error: syntax error 'https'
minio/64544db8-6334-4731-9adb-4769bce79c3f:/var/vcap/bosh_ssh/bosh_8215cf708a6f420# cat /var/vcap/monit/job/0000_minio-server.monitrc
check process minio-server
  with pidfile /var/vcap/sys/run/minio-server/pid
  start program "/var/vcap/jobs/minio-server/bin/ctl start"
  stop program "/var/vcap/jobs/minio-server/bin/ctl stop"
  group vcap
  if failed host localhost port 443 protocol https
      and request '/minio/health/live'
      with timeout 60 seconds for 5 cycles
  then restart
```

Using Xenial stemcell 170.23, Minio bosh release 2019-01-16T21-44-08Z
