### ISSUE TITLE
Minio  minio/2018-04-27T23-33-52Z & minio/2018-11-22T02-51-56Z Support Xenial Stemcell.

### ISSUE THREAD

**Issue by Muruganfly03** [minio/minio-boshrelease#124]
Hi Team,

I am using minio/2018-04-27T23-33-52Z and minio/2018-11-22T02-51-56Z in our environment which is using stemcell -
bosh-vsphere-esxi-ubuntu-trusty-go_agent/3541.34

Kindly confirm whether minio/2018-04-27T23-33-52Z and minio/2018-11-22T02-51-56Z  version support Xenial stemcell?
And also confirm from which version onwards it will start supporting Xenial stemcell?

**Comment by krishnasrinivas** [comment]
@Muruganfly03 yes all minio versions support xenial/trusty since Minio is compiled using Go everything is statically built into a single binary.
