### ISSUE TITLE
mc blob is out of date

### ISSUE THREAD

**Issue by mymasse** [minio/minio-boshrelease#131]
We tried using the mc job to pre-create our buckets and our users/policies and it failed with the following error:

`mc <ERROR> Cannot add new policy Server expects client requests with 'admin' API version 'v2', found 'v1', please upgrade the client to the latest releases`

From the commit to the repo we can see that the minio blob gets updated frequently but the mc blob hasn't received an update for more than a year

Would it be possible to update it to the latest version?

**Comment by mymasse** [comment]
Just confirmed when using bosh release `2020-01-16T22:40:29Z` the mc version packaged with it is `2018-10-18T00:40:05Z`

**Comment by krishnasrinivas** [comment]
@mymasse thanks for letting us know, we will update the `mc` binary.
