### ISSUE TITLE
Can the `mc` blob be updated to a newer version

### ISSUE THREAD

**Issue by mymasse** [minio/minio-boshrelease#169]
Not running into a specific issue but using `mc` from February 2021 seems a bit old.

Shouldn't these be auto-bumped in the repo? I wouldn't create a release but at least when MinIO itself gets auto-bumped it would include the latest `mc`.

**Comment by mymasse** [comment]
OK finally got to deploy the new version of bosh release and tried running the smoke-test errand and this failed with the following error:

```
mc: <ERROR> Invalid command usage, flag provided but not defined: -config-folder
```

**Comment by krishnasrinivas** [comment]
Updated mc. You have to wait for the next minio bosh release
