### ISSUE TITLE
Latest MinIO Bosh release on bosh.io is 2022-02-17T23-22-26Z

### ISSUE THREAD

**Issue by mymasse** [minio/minio-boshrelease#170]
It seems like bosh release have not been pushed to bosh.io since the 2022-02-17T23-22-26Z release.

**Comment by krishnasrinivas** [comment]
bosh.io will create release from the next minio release.

For now, you can do `bosh create-release --tarball=minio-release.tgz releases/minio/minio-2022-04-12T06-55-35Z.yml`
