### ISSUE TITLE
Script release creation process

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio-boshrelease#18]
Instructions mentioned in https://github.com/minio/minio-boshrelease/blob/master/MAINTAINERS.md should be scripted.

**Comment by harshavardhana** [comment]
are you still working on this @krishnasrinivas ?

**Comment by krishnasrinivas** [comment]
yes @harshavardhana

**Comment by krishnasrinivas** [comment]
make-release.sh is now available in project source.
