### ISSUE TITLE
Small typo in manifest name

### ISSUE THREAD

**Issue by Ykisialiou** [minio/minio-boshrelease#29]
Hello. I've just found a small typo, 
manifests/manfest-fs-example.yaml istead of manifests/manifest-fs-example.yaml, which I beleive should there.

**Comment by nitisht** [comment]
Thanks for reporting @Ykisialiou

**Comment by krishnasrinivas** [comment]
Looks like this is already fixed: https://github.com/minio/minio-boshrelease/blob/master/manifests/manifest-fs-example.yml
