### ISSUE TITLE
Publish new minio releases

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-boshrelease#30]
RELEASE.2017-12-28T01-21-00Z
RELEASE.2018-01-02T23-07-00Z

Tags are missing

**Comment by krishnasrinivas** [comment]
@harshavardhana bosh2 fails with:
```
Get https:/minio-bosh-blobs/eb75b6e8-ee1a-4ab4-484a-28b0ae2ef812: x509: certificate has expired or is not yet valid
```

https://pivotal.minio.io:9000/ cert has got outdated?

**Comment by harshavardhana** [comment]
Yes

**Comment by kannappanr** [comment]
Closing this issue as fixed.
