### ISSUE TITLE
the bosh release of version 2018–01–18T20–33–21Z

### ISSUE THREAD

**Issue by shaun7pan** [minio/minio-boshrelease#40]
Hi,

There is new minio RELEASE.2018–01–18T20–33–21Z announced which includes critical security fix. We are using bosh to deploy minio. May I know the plan when we can expect the bosh release version could be published ? thanks.

Best regards
Shaun

**Comment by harshavardhana** [comment]
We will soon update. Thanks for letting us know

**Comment by krishnasrinivas** [comment]
fixed by https://github.com/minio/minio-boshrelease/pull/41
