### ISSUE TITLE
Can we expose using shared NFS via Bosh

### ISSUE THREAD

**Issue by haydonryan** [minio/minio-boshrelease#45]
I found that you mention the possibility of using NFS as a backing store for Minio. 

https://github.com/minio/minio/blob/master/docs/shared-backend/DESIGN.md

I foresee a use case where I could use my Synology Nas as a backing store for my home lab since there is no s3 capability on the NAS itself.  

It would be amazing to be able to do this!

Thanks in advance.

**Comment by krishnasrinivas** [comment]
We will add a job for NFS @haydonryan 

Till then you can use `minio-server` job to expose NFS. i.e you just need the minio-server's directory to be a NFS mount point.

**Comment by haydonryan** [comment]
That'd be great, Thankyou! 

I'm not sure how to actually achieve that mount point in bosh - will do a bit of research....

**Comment by krishnasrinivas** [comment]
@haydonryan I am unable to find a BOSH document which explains how to mount a NFS export into a bosh instance. Can you check in BOSH channel? Once you figure that out you can just use `minio-server` job to use the NFS mount point.

**Comment by haydonryan** [comment]
Not a Problem. Turns out my Synology NAS (which Is why I posted this originally) is x86 based, and the Linux binary runs without modification, which has solved my problem for now. Will write it up into a blog post at some point.  Will close this.

If you do want to ask questions on bosh @krishnasrinivas jump on slack and head over to the #bosh channel at cloudfoundry.slack.com

**Comment by krishnasrinivas** [comment]
https://github.com/minio/minio-boshrelease/commit/8c4d1c262beb5e9acfc0c9eb657565e4231bc8dc
