### ISSUE TITLE
Minio object storage for application data

### ISSUE THREAD

**Issue by abhilash07** [minio/minio-boshrelease#50]
Hi is everyone tried to deploy Minio on CF Market place using on-Demand-Broker and Service Adapter or
as Cloud Foundry Blobstore.
Thanks in Advance. 
Abhilash S

https://www.minio.io/cloudfoundry.html

**Comment by krishnasrinivas** [comment]
@abhilash07 yes I have tried and it works. If you are facing any issues let us know.

**Comment by abhilash07** [comment]
@krishnasrinivas thanks for you information.

**Comment by krishnasrinivas** [comment]
you dont need yaml file when you use tile @abhilash07 check the docs here https://docs.pivotal.io/partners/minio/index.html for Minio Tile

**Comment by abhilash07** [comment]
@krishnasrinivas what is the stemcell version you used for deploying on pivotal. i am encountering below error for on on-demand-service-broker-0.20.0.

<img width="1421" alt="screen shot 2018-04-13 at 9 37 44 am" src="https://user-images.githubusercontent.com/10971841/38711544-3c8eae0c-3f01-11e8-9723-60aecc717777.png">

**Comment by krishnasrinivas** [comment]
@abhilash07 you will need to use :

stemcell_criteria:
  os: 'ubuntu-trusty'
  version: ' 3468.17'   

let us know if it worked.

**Comment by abhilash07** [comment]
@krishnasrinivas thanks for the info can you please let me know on which IaaS did you deploy (AWS, Azure or Openstack etc.)

**Comment by abhilash07** [comment]
@krishnasrinivas i deployed on azure using both 3468.17 and 3468.30 but i am facing same error.

How can we know the on-demand-service-broker support the exact stemcell, i mean any documentation ??? 

Thanks in Advance

**Comment by krishnasrinivas** [comment]
@abhilash07 we are in touch with Pivotal for this issue. They are exploring if this is an issue with Pivotal on Azure.

**Comment by abhilash07** [comment]
@krishnasrinivas i solved the problem. thanks for your suggestions. 

I am curious, did you try minio on-demand-service-broker & adapter deployment on open source cloud foundry ???

Thanks in advance.

**Comment by krishnasrinivas** [comment]
> I am curious, did you try minio on-demand-service-broker & adapter deployment on open source cloud foundry ???

@abhilash07 no, do you think it will be useful?

**Comment by abhilash07** [comment]
@krishnasrinivas yes it is much waited service. Becuase upto now there are many storage services, but minio is the best sollution up to now. Because of tenant, ha? Zerodowntime features. Moreover minio is much needed backend services for cf applications

**Comment by krishnasrinivas** [comment]
@abhilash07 can you open a new issue for that please?

**Comment by gberche-orange** [comment]
@krishnasrinivas is there a public repo for the ODB service adapter code, that could enable use this service on a CF OSS setup (along with a minio enterprise license)? Currently I only found the binary PCF tile in https://network.pivotal.io/products/minio and an early broker skeleton on https://github.com/krishnasrinivas/minio-service-broker

**Comment by krishnasrinivas** [comment]
@gberche-orange Here: https://github.com/minio/minio-boshrelease/issues/64 it was mentioned that the PCF tile itself can be used for open-source CF, is that the case? If not what does it take to author a tile for Open Source CF? If the service adapter is open source, how can you fix it to make it work with open source CF?

**Comment by gberche-orange** [comment]
@krishnasrinivas 

> Is there any doc on how it can be packaged to run on CF OSS? Basically I need a doc on how to create a tile for OSS CF.

There is no concept of a tile for CF oss. OSS operators would use bosh to deploy the ODB release and the adapter. See for example https://github.com/pivotal-cf-experimental/redis-example-service-adapter-release#setting-up-the-redis-adapter-with-the-on-demand-service-broker redis sample and associated manifest.

For minio adapter to be useable to the CF OSS community, the easiest thing is probably to opensource the adapter bosh release source code, from which OSS users can build a local bosh release and deploy it.

**Comment by krishnasrinivas** [comment]
@gberche-orange https://github.com/minio/minio-pcf-adapter is the service adapter. Will you be able to help on documenting how it can be deployed on the opensource CF? We do not have much experience with CF internals.

**Comment by krishnasrinivas** [comment]
@gberche-orange you can catch us on slack.minio.io too if it is convenient for you. Closing this issue.
