### ISSUE TITLE
smoke-tests job

### ISSUE THREAD

**Issue by cppforlife** [minio/minio-boshrelease#51]
would be nice to have an errand job so that it's easy to verify that system is working properly. see example for smoke-test in https://github.com/cppforlife/zookeeper-release#zookeeper-bosh-release

**Comment by krishnasrinivas** [comment]
@cppforlife smoke-tests will be good to have. Thanks for the pointer to the zookeeper bosh release. We'll have have smoke tests soon.

**Comment by abhilash07** [comment]
@cppforlife, @krishnasrinivas hope this will helpfull for you. 

https://github.com/shinji62/minio-dist-boshrelease/tree/master/jobs/smoke-tests

**Comment by krishnasrinivas** [comment]
Thanks @abhilash07

**Comment by harshavardhana** [comment]
Fixed by #70
