### ISSUE TITLE
Minio cluster deployed using this release does not self-heal

### ISSUE THREAD

**Issue by CAFxX** [minio/minio-boshrelease#55]
[After the deploy is complete](https://bosh.io/docs/post-deploy.html) minio should automatically self-heal.

**Comment by harshavardhana** [comment]
Minio doesn't self heal - you need to heal manually. Using `mc admin heal`

**Comment by CAFxX** [comment]
@harshavardhana sure, I know that. But the given post-deploy hook I linked above it should be pretty easy to implement a script that, once the deploy is over, triggers `mc admin heal`, thereby "self-healing" the minio cluster.

When eventually minio will evolve a bit and grow proper self-healing then what I'm proposing here won't be needed anymore - but until then...

**Comment by harshavardhana** [comment]
We won't be doing self-healing in Minio - we intentionally didn't implement it.  So a script based is perhaps okay.

**Comment by kannappanr** [comment]
@CAFxX  Thanks for contacting us. We will be closing this issue as won't fix.
