### ISSUE TITLE
Provide a health_check script

### ISSUE THREAD

**Issue by rkoster** [minio/minio-boshrelease#6]
When using minio with CF, it is usefull to register a route for it with the gorouter.
For this the routing release provides the [route_registrar](https://github.com/cloudfoundry-incubator/routing-release/tree/develop/jobs/route_registrar) job. For the best result the `route_registrar` should be configured with a `health_check` script.

The CF UAA is [for example](https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L419-L421) configured like this. And the health check script is provided by the UAA release [here](https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/templates/health_check). 

This issue could be related to: https://github.com/minio/minio/issues/3800

**Comment by krishnasrinivas** [comment]
thanks @rkoster we'll provide a health_check script just like https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/templates/health_check

We'd be happy to receive a PR too.

**Comment by rkoster** [comment]
🎉
