### ISSUE TITLE
Minio adapter for Cloud Foundry application data

### ISSUE THREAD

**Issue by abhilash07** [minio/minio-boshrelease#64]
Hi everyone is there any roadmap  to develop Minio Service Adapter  for Open Source Cloud Foundry Application Data. (#50 )

I have noticed PCF is developed, and make it as General Availability. (https://docs.pivotal.io/partners/minio/architecture.html). I think We can use it on OS Cf also.

Any Suggestioons please  ???

**Comment by krishnasrinivas** [comment]
If you know more users who want this and if they can comment on this issue to let us know it will be easier to prioritize the issue.

**Comment by abhilash07** [comment]
@krishnasrinivas, sure. But i think we don't need development of Minio adapter for Cloud Foundry application data. 

Because pivotal released minio tile on General Availability license. We can use the same adapter.

**Comment by krishnasrinivas** [comment]
> Because pivotal released minio tile on General Availability license. We can use the same adapter.

Are you saying you can use the Pivotal tile on open source Cloud Foundry? In that case should we close this issue?

**Comment by abhilash07** [comment]
@krishnasrinivas, yes you're right, i think we can close this issue
