### ISSUE TITLE
seeding buckets

### ISSUE THREAD

**Issue by poblin-orange** [minio/minio-boshrelease#65]
data related bosh-release usually offer the ability to seed database at bosh deploy time.

Adding spec to minio jobs to automatically create bucket would be very usefull (avoids users to use another automation tool to complete the minio bosh deployment), with minio related ACL configuration.
see this example : https://github.com/cloudfoundry/postgres-release/blob/develop/jobs/postgres/spec#L45

**Comment by krishnasrinivas** [comment]
Looks like a useful feature.

**Comment by krishnasrinivas** [comment]
https://docs.pivotal.io/tiledev/1-12/tile-errands.html

>Typical post-install errands include smoke or acceptance tests, database initialization or database migration, and service broker registration.

@poblin-orange https://github.com/minio/minio-boshrelease/blob/master/manifests/manifest-fs-example.yml check for bucket-seeding instance group.

**Comment by poblin-orange** [comment]
@krishnasrinivas very nice :-) thks
