### ISSUE TITLE
scaling up and down error 

### ISSUE THREAD

**Issue by abhilash07** [minio/minio-boshrelease#66]
hi i am deploying this release in bosh but when i deployed  (https://github.com/minio/minio-boshrelease/blob/master/manifests/manifest-dist-example.yaml) 1 and scale UP to 4 hosts occurring below error.

[minio-server.stdout-1~4.log](https://github.com/minio/minio-boshrelease/files/1982335/minio-server.stdout-1.4.log)

when i deployed using (https://github.com/minio/minio-boshrelease/blob/master/manifests/manifest-dist-example.yaml) 4 hosts and scaling UP to 8 or 12 hosts i am getting below errors

[minio-server.stdout-4~8.log](https://github.com/minio/minio-boshrelease/files/1982327/minio-server.stdout-4.8.log)

[minio-server.stdout-8~12.log](https://github.com/minio/minio-boshrelease/files/1982328/minio-server.stdout-8.12.log)

when i deployed using (https://github.com/minio/minio-boshrelease/blob/master/manifests/manifest-dist-example.yaml) 4 hosts and scaling DOWN to 1 hosts i am getting below errors

[minio-server.stdout-4~1.log](https://github.com/minio/minio-boshrelease/files/1982343/minio-server.stdout-4.1.log)

is this error related to minio distrubuted & erasure algorithms ???

Any idea to solve this problem ???. Thanks in advance

**Comment by harshavardhana** [comment]
@abhilash07 you cannot add disks/nodes to existing deployments.

**Comment by abhilash07** [comment]
@harshavardhana thanks for your responce i can attach disk, if i scale up for example (1~4) or (4~8) or (8~12) i am getting above errors.
As we know in bosh if we make changes for one instance it will update all the respective instances, in that case minio erasure algorithm has some problem to upfate.
But i am not sure, becuase i am new to minio. 
Thanks in advance.

**Comment by abhilash07** [comment]
@harshavardhana, when we scale UP the minio instances bosh will update from 1 instance to 4rth instance. I think minio erasure algorithm is trying to format instance1 disk which is already running erasure deployment.

**Comment by abhilash07** [comment]
as discussed in https://github.com/minio/minio/issues/5901 minio can't scale up and down in existing deployment by its design.

as i checked deploying multiple deployment servers and attaching to LB is not bad idea.
 https://www.nginx.com/blog/enterprise-grade-cloud-storage-nginx-plus-minio/
But i am thinking is data synchronisation possible between multiple deployment minio servers with LB ???

Any one tried this Architecture ???

**Comment by krishnasrinivas** [comment]
You can refer to this doc https://docs.minio.io/docs/minio-client-complete-guide#mirror for mirroring data between two minio deployments.

Closing this issue.
