### ISSUE TITLE
Add an entry in Github 'releases' section for each final releases

### ISSUE THREAD

**Issue by bgandon** [minio/minio-boshrelease#67]
Hi,

Could you please add an entry in the [releases](https://github.com/minio/minio-boshrelease/releases) section for the latest final BOSH release that has been cut `2018-04-27T23-33-52Z` and any upcoming subsequent releases?

The BOSH community usually adds one entry in the 'releases' section for each final release [listed on BOSH.io](https://bosh.io/releases/github.com/minio/minio-boshrelease?all=1), and it's a good place to put release notes. As an example, here are the [release notes for Cassandra](https://github.com/orange-cloudfoundry/cassandra-cf-service-boshrelease/releases) that I write.

Best,

**Comment by patrickcrocker** [comment]
I'm a big fan of tracking everything in a [changelog](https://github.com/nulldriver/cf-cli-resource/blob/master/CHANGELOG.md) and then using a pipeline to [parse and publish](https://github.com/nulldriver/cf-cli-resource/blob/master/pipeline.yml#L81) the release notes to github.

**Comment by krishnasrinivas** [comment]
@bgandon @patrickcrocker Since we put the change-log/release-notes here https://github.com/minio/minio/releases, we were not duplicating the information here.

But looks like it will be useful to duplicate the information on https://github.com/minio/minio-boshrelease/releases as well as minio-bosh users tend to look at minio-boshrelease repo for change log information. We will do it from the next release.

**Comment by bgandon** [comment]
Using a CHANGELOG.md that is parsed by some automation is great indeed!

Yes indeed, duplicating the info would be perfect.
In the meanwhile, could you just edit existing releases of this minio BOSH release and add a pointer to the relevant minio daemon release notes? Thank you!

**Comment by bgandon** [comment]
Also, the following versions of the BOSH Release have no Git tags:

- 2018-01-18T20-33-21Z
- 2018-02-09T22-40-05Z
- 2018-03-12T21-25-28Z
- 2018-03-19T19-22-06Z
- 2018-04-19T22-54-58Z
- 2018-04-27T23-33-52Z

It would be nice to push some tags so that they appear in [minio-boshrelease/releases](https://github.com/minio/minio-boshrelease/releases).

**Comment by krishnasrinivas** [comment]
We have added the release details for the latest release.

**Comment by bgandon** [comment]
Thank you!
