### ISSUE TITLE
Error: Unable to load config version: '23'.

### ISSUE THREAD

**Issue by abhilash07** [minio/minio-boshrelease#68]
hi i want to deploy minio-server on 4 hosts with single disk. I used (https://github.com/minio/minio-boshrelease/blob/master/manifests/manifest-dist-example.yaml) distributed deployment.

And i want to change storageclass.standard  (EC:3) && storageclass.rrs (EC:1) i followed below this https://docs.minio.io/docs/minio-server-configuration-guide.

But unfortunately i encountered this error.
Error: Unable to load config version: '23'.
Please refer my config file in below.
[config.txt](https://github.com/minio/minio-boshrelease/files/2011245/config.txt)

Thanks in Advance.

**Comment by kannappanr** [comment]
@abhilash07 Did you resolve the issue? Looking from the error, it looks like the config file on the system is newer than the one supported by the minio server. You can either upgrade to the latest version of minio or remove the config file, so that it can generate it again.

**Comment by abhilash07** [comment]
@kannappanr thanks for your responce, i will try and let you know.

Regards

Abhilash S

**Comment by abhilash07** [comment]
@kannappanr thanks for your information,, i used minio version = 2018-05-16T23-35-33Z and config version = 23 it works. I am closeing the error.
[config.txt](https://github.com/minio/minio-boshrelease/files/2038382/config.txt)
