### ISSUE TITLE
Unable to load the configuration file

### ISSUE THREAD

**Issue by abhilash07** [minio/minio-boshrelease#69]
Hi after clearing error #68 i configured standard storage and Reduced redundancy storage (rrs), but i get below errors

1) 6 vm deployment 1 disk respectively standard storage = 4 rrs = 2
Error:
Unable to load the configuration file: Standard storage class parity 4 should be less than or equal to 3.

2) 4 vm deployment 1 disk respectively Standard storage = 4 rrs = 0
Error
Unable to load the configuration file: Standard storage class parity 4 should be less than or equal to 2

3) 4 vm deployment 1 disk respectively Standard storage = 3 rrs = 1

Unable to load the configuration file: Reduced redundancy storage class parity 1 should be greater than or equal to 2

I have few questions to know:

1) Is minio can support only Standard storage by disbaling Reduced redundancy storage ?

2) Is minio can support only Reduced redundancy storage  by disbaling  Standard storage ?

3) When i deployed 4 vms is minio supports 3 Standard storage and 1 rrs or vice versa ?

Thanks in advance 

Abhilash S

**Comment by kannappanr** [comment]
@abhilash07 Please refer to `Storage Class` section in https://docs.minio.io/docs/minio-server-configuration-guide , https://blog.minio.io/configurable-data-and-parity-drives-on-minio-server-2a34cd49c1b5 and  https://github.com/minio/minio/blob/master/docs/erasure/storage-class/README.md . 

As far as your questions are concerned,
1. Is minio can support only Standard storage by disbaling Reduced redundancy storage ?

No. You can refer to the document for further explanation.

2. Is minio can support only Reduced redundancy storage by disbaling Standard storage ?
No again.

3. When i deployed 4 vms is minio supports 3 Standard storage and 1 rrs or vice versa ?
I guessing that you have an understanding that Standard Storage means number of data drives and reduced redundancy storage means number of parity drives.

Those docs should help you out in your setup. Let us know otherwise.

**Comment by abhilash07** [comment]
@krishnasrinivas thanks for your quick response. But unfortunately i already read your above documentation and articles. So i stated testing i encounter above errors. After thinking and referring above doc and articles parity disks will support for only 16 disks if i am not wrong  ???.

Thanks in advance 

Abhilash S

**Comment by kannappanr** [comment]
@abhilash07 
In the first scenario, the standard storage cannot be greater than 3, just as the error suggests. 
`6 vm deployment 1 disk respectively standard storage = 3 rrs = 2`

 It is the same with the second setup, it cannot be greater than 2 (N/2).
`4 vm deployment 1 disk respectively Standard storage = 2 rrs = 0`

In the third scenario, parity 
`4 vm deployment 1 disk respectively Standard storage = 2 rrs = 0`

quoting from https://github.com/minio/minio/blob/master/docs/erasure/storage-class/README.md   `As parity below 2 is not recommended, REDUCED_REDUNDANCY storage class is not supported for 4 disks erasure coding setup.`

**Comment by abhilash07** [comment]
@kannappanr, thanks for you explanation, Now i understand i will test and  update the status.

Thanks in Advance

Abhilash S

**Comment by abhilash07** [comment]
@kannappanr, i think in minio two should be considered in high priority.

1) Scaling the existing Minio server deployment. (For example if we deploy 4vm Minio server, there should be production case where we have to scale up-to 12 VMs with each disk respectively). Because in Cloud infrastructure scaling plays a keys role.

2) Second one, there should be flexibility in selecting Standard storage and Reduced redundancy storage (not fixed to N/2), for user needs.

Thanks in advance

**Comment by krishnasrinivas** [comment]
> Second one, there should be flexibility in selecting Standard storage and Reduced redundancy storage (not fixed to N/2), for user needs.

It is flexible @abhilash07 you can set it through the env vars:
```
export MINIO_STORAGE_CLASS_STANDARD=EC:3
export MINIO_STORAGE_CLASS_RRS=EC:2
```

as explained in the blog https://blog.minio.io/configurable-data-and-parity-drives-on-minio-server-2a34cd49c1b5

**Comment by harshavardhana** [comment]
> Second one, there should be flexibility in selecting Standard storage and Reduced redundancy storage (not fixed to N/2), for user needs.

As explained by @krishnasrinivas it is configurable but 4 disks have little room for such experiments, as you can see we do not allow incorrect configurations as it is our intention to error on user mistakes which might lose your data. 

As for scalability Minio is designed to be scalable in deployment units, basically if you want to increase the number of nodes simply start another set of machines and point your application to the new server.  WIth upcoming federation feature you can also combine these disparate clusters into a single pool allowing for simpler expansion.
