### ISSUE TITLE
Can't scale from 1 node to 4

### ISSUE THREAD

**Issue by ljfranklin** [minio/minio-boshrelease#74]
While testing or for cost reasons, it's often useful to start with a small 1 node deployment and scale to 4 nodes once things are working. However, we're hitting an error message while scaling up. We can successfully deploy with 1 node, but when we change to `instances: 4` in our manifest and re-deploy, the first node fails to deploy with:

```
ERROR Unable to initialize backend: Disk /var/vcap/store/minio-server: found backend fs, expected xl.
```

Is this a supported workflow in Minio or possibly a mistake in the BOSH release packaging?

**Comment by krishnasrinivas** [comment]
This is an expected behavior @ljfranklin Minio should be initialized and used as a static unit set. Minio took this approach to build for very large scale. design philosophy is to build many small manageable units rather than one giant monolithic distributed unit.

**Comment by ljfranklin** [comment]
@krishnasrinivas good to know, thanks for the quick response! Closing this out as things are working as intended.
