### ISSUE TITLE
Minio update 2018-04-27T23-33-52Z to 2018-06-08T03-49-38Z ... web-ui storage not calculated

### ISSUE THREAD

**Issue by penrod** [minio/minio-boshrelease#77]
Updated minio boshrelease from 2018-04-27T23-33-52Z to 2018-06-08T03-49-38Z. The backend storage is nfs, so we are running minio-nas. 

Pre-update the released would show storage capacity used and capacity available at the top of the web-ui. 

Post-update the capacity at the top shows  "Used: 0.00 PB"

All other functions are working as expected (file write/read, create/delete, etc)

We only updated the minio boshrelease. 

Capi: 
http://bosh.io/d/github.com/cloudfoundry/capi-release?v=1.59.0

Stemcell:
vsphere trusty 3541.24

Any ideas?

**Comment by harshavardhana** [comment]
This is on purpose @penrod we deprecated the total/free which was at disk level to per tenant total used. Total used is like `du` per Minio cluster.  If you have a lot of data it might take some time for this to be calculated.

**Comment by penrod** [comment]
Interesting. I may have something in my configuration that is not allowing that to work correctly. The value shows 'Used: 20.05 KB' even though I have over 6 GB of files on it. Adding new files does not change the usage value.

**Comment by harshavardhana** [comment]
> Interesting. I may have something in my configuration that is not allowing that to work correctly. The value shows 'Used: 20.05 KB' even though I have over 6 GB of files on it. Adding new files does not change the usage value.

New files don't get updated, the usage check runs every 12 hrs.

**Comment by kannappanr** [comment]
@penrod Closing this issue as answered. Please feel free to reopen the issue if you feel otherwise.
