### ISSUE TITLE
Could you publish releases

### ISSUE THREAD

**Issue by mkuratczyk** [minio/minio-boshrelease#8]
Hey. Would it be possible to publish the releases (.tgz files) on GH and/or bosh.io/releases?

**Comment by poornas** [comment]
@mkuratczyk , attaching the latest release here. We will be submitting this to https://bosh.io/releases soon. We would love to pick your brain on how you use minio-boshrelease for your workflow. If you have a few minutes to jump on a call with us , or drop by (we are in Palo Alto,CA) it would  help us understand how we can improve this package further to align with typical usage by cloudfoundry users such as yourself. Looking forward to hearing from you.
[minio.zip](https://github.com/minio/minio-boshrelease/files/1213039/minio.zip)

**Comment by mkuratczyk** [comment]
Thank you. I had built the release myself before raising the issue - it's ok as a one-off solution. However, we want to mirror all used BOSH releases to a local Artifactory and currently there is no-where to mirror minio-boshrelease from. Feel free to contact me regarding how we are using Minio.

**Comment by poornas** [comment]
@mkuratczyk , would you be able to spare 20 minutes tomorrow for a quick call? If you could join us on https://slack.minio.io, we can set up a call. Thanks!

**Comment by krishnasrinivas** [comment]
@mkuratczyk it is available here https://github.com/minio/minio-boshrelease/releases, it will also be available bosh.io/releases soon

**Comment by mkuratczyk** [comment]
Great, thank you.

**Comment by poornas** [comment]
@mkuratczyk, minio-boshrelease is now available on http://bosh.io/releases
