### ISSUE TITLE
Changing credential in manifest does not change running config of minio-server on subsequent deploy

### ISSUE THREAD

**Issue by dlinsley** [minio/minio-boshrelease#85]
Seen in release "2018-07-10T01-42-11Z"

Initial deployment using sample manifest (manifests/manifests-fs-example.yml) works great.

If I modify the credential property (accesskey /secretkey) of minio-server job and deploy again, the change isn't realized.

BOSH CLI recognized the change and prompts for confirmation.  Running service still using original credentials.

Tried issued a recreate VMs command.  Same result, Original credential in place.

Needed to delete and recreate the deployment to make this change via the deployment manifest.

**Comment by poornas** [comment]
@dlinsley, running minio instance needs to be restarted for credential change to take effect. which version of the BOSH CLI tool are you using? Did you do a bosh deploy --recreate or bosh recreate JOB [INDEX]

**Comment by poornas** [comment]
@dlinsley , as a workaround you could update the credentials via  minio web browser [ui](https://docs.minio.io/) by clicking on settings and Change Password.  We will get back to you on being able to modify credentials via deployment manifest.

**Comment by dlinsley** [comment]
@poornas Yes, as an attempted workaround I issued a `bosh recreate` which recreated the VM.  The credentials remained the same.

I also tried a `bosh stop GROUP` and a `bosh start GROUP` but still did not observe the credential change.

**Comment by krishnasrinivas** [comment]
@dlinsley recreating the VM would not be desirable for you. Easy way to change the credentials is using the web-ui minio browser. The UI can be accessed at "http://minioIP:9000/"
