### ISSUE TITLE
smoke-tests errand fails if credential.secretkey contains a #

### ISSUE THREAD

**Issue by teddyking** [minio/minio-boshrelease#90]
We deployed minio using the sample manifest [here](https://github.com/minio/minio-boshrelease/blob/master/manifests/manifest-fs-example.yml), with `credential.secretkey` that included a `#`. When we tried to run the smoke-tests errand, it then failed with the following:

```
Instance   tests/fa1ccf19-8994-4f6b-870d-451d7d6d7df6
Exit Code  0
Stdout     -
Stderr     mc: <ERROR> Invalid target `myminio/test`. Invalid arguments provided, please refer `mc <command> -h` for relevant documentation.


1 errand(s)

Succeeded
```

The errand also reported as `Succeeded`. We think this is because [this env var](https://github.com/minio/minio-boshrelease/blob/02589ee23cff474355f820ace13cb49ffeac00f2/jobs/smoke-tests/templates/run.erb#L9) is not URL encoded. Is this a known issue?

**Comment by kannappanr** [comment]
@teddyking Thanks for filing this issue. The script should have url encoded the secret key and access key if it is allowed. We will fix it on our end so that `#` is now handled.

**Comment by krishnasrinivas** [comment]
Keeping it open till mc is updated in the bosh-release pacakge
